### PR TITLE
Set Strip URI to false upon creation of API in Kong

### PR DESCRIPTION
**Pull request by paniagua**
[Strip URI](https://getkong.org/docs/0.10.x/proxy/) It may be desirable to specify a URI prefix to match an API,
but not include it in the upstream request.

It means that if the request is `/omnicall/path` it removes the
`/omnicall` piece, which is not desired.

The default value is `true`. This PR forces the paremeter to be `false`

### CODE REVIEW

**Comment by indrekj** [comment]
Can this value be changed in the Ingress file instead? I'd prefer not to start managing another load balancer ourselves.

**Comment by paniagua** [comment]
no, it cant. 

I agree, it is not ideal, but the current implementation from koli does not support to read this from the ingress spec.

**Comment by indrekj** [comment]
Do you have a plan to create an upsteam PR to set the default or to make it configurable?

**Comment by paniagua** [comment]
alternatively we can remove the prefix `/omnicall` in the `phone-manager-system`

An integrator would still use the prefix

**Comment by paniagua** [comment]
> Do you have a plan to create an upsteam PR to set the default or to make it configurable?
Possibly but after I can handle it over to Inf.

**Comment by indrekj** [comment]
Also, CallRouter actually requires to Strip the URL. So fixing PNM would break CallRouter if I understand correctly. I think we need to make it configurable first.

**Comment by paniagua** [comment]
ingress aside-

why do we have different approaches in stripping/not stripping the url ?

Also, CallRouter actually requires to Strip the URL

**Comment by indrekj** [comment]
> why do we have different approaches in stripping/not stripping the url ?

It's up to the service which suits better. We can't strip legacy api paths because they're legacy and are being used. Call router was a new and dedicated service and tm-engage (cc @take-five) decided not to add a redundant prefix for each route. I guess we could add the prefix to call router as well, but the proxy/ingress should be smart enough to know how to rewrite urls when requested.

**Pull request closed without merging**
